### ISSUE TITLE
Error code 127 for R CMD CHECK is taken as success

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/staged-dependencies-action#16]
https://github.com/insightsengineering/teal.transform/runs/7425907522?check_suite_focus=true

![image](https://user-images.githubusercontent.com/15201933/179949104-eddd193a-37e0-4149-b43c-3e2342f47ef4.png)

**Comment by dinakar29** [comment]
Closing as this is impertinent to this action.
